# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: 체크아웃
        uses: actions/checkout@v3

      # ─── Frontend ───
      - name: Node.js 셋업 (frontend)
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: client/package-lock.json

      - name: 프론트엔드 의존성 설치
        run: npm ci
        working-directory: client

      - name: 프론트엔드 Lint & Test
        run: npm run lint
        working-directory: client

      - name: 프론트엔드 빌드
        run: npm run build
        working-directory: client

      # ─── Serverless API ───
      - name: Node.js 셋업 (API)
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: API 의존성 설치
        run: npm ci
        working-directory: vercel_serverless/api

      - name: API 빌드
        run: npm run build
        working-directory: vercel_serverless/api
