# .github/workflows/deploy-vercel.yml
name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  vercel-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Vercel에 배포
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Vercel Personal Token
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # Vercel Org ID
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # Vercel Project ID
          working-directory: ./client
          prod: true
